<?php

namespace App\Livewire;

use App\ConversationStatus;
use App\Models\Conversation;
use Livewire\Attributes\Url;
use Livewire\Component;

class ConversationDetailPage extends Component
{
    #[Url]
    public int $conversation_id;

    public string $status = '';

    public bool $showFullConversation = false;

    public function mount(): void
    {
        $conversation = Conversation::findOrFail($this->conversation_id);

        $this->authorize('view', $conversation);

        $this->status = $conversation->status->value;
    }

    public function updateStatus(): void
    {
        $conversation = Conversation::findOrFail($this->conversation_id);

        $this->authorize('update', $conversation);

        $validated = $this->validate([
            'status' => 'required|string',
        ]);

        $conversation->update(['status' => ConversationStatus::from($validated['status'])]);

        $this->status = $conversation->fresh()->status->value;
    }

    public function downloadDocument(int $documentId)
    {
        $conversation = Conversation::findOrFail($this->conversation_id);

        $this->authorize('view', $conversation);

        $document = $conversation->documents()->findOrFail($documentId);

        $filename = str($document->name)->slug()->append('.md')->toString();

        return response()->streamDownload(function () use ($document) {
            echo $document->content;
        }, $filename, [
            'Content-Type' => 'text/markdown',
        ]);
    }

    public function downloadDocumentAsHtml(int $documentId)
    {
        $conversation = Conversation::findOrFail($this->conversation_id);

        $this->authorize('view', $conversation);

        $document = $conversation->documents()->findOrFail($documentId);

        $html = str($document->content)->markdown([
            'html_input' => 'strip',
            'allow_unsafe_links' => false,
        ]);

        $filename = str($document->name)->slug()->append('.html')->toString();

        $htmlDocument = <<<HTML
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>{$document->name}</title>
            <script src="https://cdn.tailwindcss.com"></script>
            <script>
                tailwind.config = {
                    theme: {
                        extend: {
                            colors: {
                                'uofg-blue': '#011451',
                                'uofg-burgundy': '#961E50',
                                'uofg-rose': '#C85C8E',
                                'uofg-mocha': '#7C6A5C',
                                'uofg-sandstone': '#C7B299',
                                'uofg-slate': '#5C6F81',
                                'uofg-teal': '#006579',
                                'uofg-turquoise': '#009396',
                                'uofg-lime': '#CBDB2A',
                                'uofg-cobalt': '#0066CC',
                            }
                        }
                    }
                }
            </script>
            <link rel="stylesheet" href="https://unpkg.com/@tailwindcss/typography@0.5.15/dist/typography.min.css">
            <style>
                body {
                    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
                }
                .prose h1, .prose h2 {
                    color: #011451;
                }
                .prose h3, .prose h4 {
                    color: #5C6F81;
                }
            </style>
        </head>
        <body class="bg-gray-50 py-8 px-4">
            <div class="max-w-4xl mx-auto bg-white shadow-lg rounded-lg p-8">
                <div class="mb-6 border-b border-gray-200 pb-4">
                    <h1 class="text-3xl font-bold text-uofg-blue">{$document->name}</h1>
                    <p class="text-sm text-gray-600 mt-2">Created: {$document->created_at->format('F j, Y g:i A')}</p>
                </div>
                <div class="prose prose-lg max-w-none">
                    {$html}
                </div>
                <div class="mt-8 pt-6 border-t border-gray-200 text-center text-sm text-gray-500">
                    <p>Generated by Reqqy &mdash; University of Glasgow</p>
                </div>
            </div>
        </body>
        </html>
        HTML;

        return response()->streamDownload(function () use ($htmlDocument) {
            echo $htmlDocument;
        }, $filename, [
            'Content-Type' => 'text/html',
        ]);
    }

    public function render()
    {
        $conversation = Conversation::with(['user', 'application', 'messages', 'documents'])
            ->findOrFail($this->conversation_id);

        return view('livewire.conversation-detail-page', [
            'conversation' => $conversation,
            'statuses' => ConversationStatus::cases(),
        ]);
    }
}
